# **Assignment 5**
***Eric Johansson & Max Sonnelid***

Hours spent: 15 hours per person 

In [ ]:
Key words: Reinforcement learning, optimal path algorithm, value iteration, optimal policy, Q-learning, AI gym

# Question 1

1a)

Optimal path is either: **EENNN** or **EENNWNE**. Since there are two different paths, there does not exist an unique solution. However, if $\gamma$ < 1 (the discounting rate is less than zero), the first path (EENNN) would uniquely be the optimum as the optimum is reached faster than in the second alternative.

Both of these paths will result a **total reward** of 0.



1b)

We define all the states as the following matrix, where (0,0) is the starting state and (2,2) is the exit state.



```
[(0,3) (1,3) (2,3)
(0,2) (1,2) (2,2)
(0,1) (1,1) (2,1)
(0,0) (1,0) (2,0)]
```




Policy for each state:


(0,0) = E 

(0,1) = E or N

(0,2) = E or N

(0,3) = E or N

(1,0) = E

(1,1) = E or N

(1,2) = E or N

(1,3) = S or E

(2,0) = N

(2,1) = N

(2,2) = N or E


By following this policy, an optimal solution will be reached regardless of what start point that is selected. Note that optimal value can differ depending on what point that is selected as starting point

What is intersting to note is that the optimal policy can be reach with fewer iterations compared with optimal values. Therefore, if only the optimal policy is required, a lot of computing power could be saved by only focusing on optimal policy. 

1c)

If starting point is set to (0,0) the expected reward with optimal solution is 0. However, the expected reward is different among the starting points, for example (1,0) will result in a optimal solution 1.

# Question 2

2a)

In [ ]:
#Create the reward matrix
import numpy as np
matrix =  np.arange(2.0, 11.0).reshape(3,3)
#print(x)

for i in range(0,3):
    for j in range (0,3):
        matrix[i][j] = 0.0


matrix[1][1]=10.0
print(matrix)

[[ 0.  0.  0.]
 [ 0. 10.  0.]
 [ 0.  0.  0.]]


In [ ]:
#Method for checking whether a step is feasible or not
#If step is not feasible, return 0
def testStep(matrix, x, y, dir):
    if dir == 'N':
        if x-1<0:
            return 0
        else: return matrix[x-1][y]
    if dir == 'S':
        if x+1>2:
            return 0
        else: return matrix[x+1][y]
    if dir == 'E':
        if y+1>2:
            return 0
        else: return matrix[x][y+1]
    if dir == 'W':
        if y-1<0:
            return 0
        else: return matrix[x][y-1]

In [ ]:
#Calculate the expected reward for each possible action in a certain state
#This is based both on the potential current reward and the discounted historical potential reward
#The highest expected reward for any of the possible actions is returned
def maxValue_new(x, y, original, updated):
    N = 0.8*(testStep(original,x,y,'N')+0.9*testStep(updated,x,y,'N'))+0.2*(original[x][y]+0.9*updated[x][y])
    S = 0.8*(testStep(original,x,y,'S')+0.9*testStep(updated,x,y,'S'))+0.2*(original[x][y]+0.9*updated[x][y])
    E = 0.8*(testStep(original,x,y,'E')+0.9*testStep(updated,x,y,'E'))+0.2*(original[x][y]+0.9*updated[x][y])
    W = 0.8*(testStep(original,x,y,'W')+0.9*testStep(updated,x,y,'W'))+0.2*(original[x][y]+0.9*updated[x][y])
    return (max(N,S,E,W))


In [ ]:
#An 3x3 matrix filled with only 0 is created
def empty_matrix():
    res =  np.arange(2.0, 11.0).reshape(3,3)

    for i in range(0,3):
         for j in range (0,3):
              res[i][j] = 0.0
    return res

print(empty_matrix())

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
MI6 =  np.arange(73.0, 82.0).reshape(3,3)
MI6.astype(float)
print(M16)

[[73. 74. 75.]
 [76. 77. 78.]
 [79. 80. 81.]]


In [ ]:
#Method for performing value iteration based on the problem described in question 2 in the assignment
def iterate(nr, start_matrix):
    temp = empty_matrix() #Start with an empty matrix

    for i in range(0,3):
        for j in range (0,3):
            #Based on the start_matrix (reward matrix), calculate the expected reward for each state in one iteration
            #Replace empty_matrix() with MI6 if you want to have initial value other than zero
            temp[i][j] = maxValue_new(i, j, start_matrix, empty_matrix())
    if (nr > 1):
        for i in range(nr-1):  #Number of iterations for calculating the reward matrix
            temp2 = empty_matrix()
            for i in range(0,3):
                 for j in range (0,3):
                      #Based on the start_matrix (reward matrix) and temp (expected reward matrix from last iteration), calculate the expected reward for each state
                      temp2[i][j] = maxValue_new(i, j, start_matrix, temp) 
            temp = temp2
    return temp #Return the reward matrix calculated based on n iterations

print(iterate(14000,matrix))

[[45.61292366 51.94805195 45.61292366]
 [51.94805195 48.05194805 51.94805195]
 [45.61292366 51.94805195 45.61292366]]


The value function for each state will converge to the value as shown in the picture below. The optimal policy for each state is also shown in the picture as arrows pointing in the direction with the highest expected reward.

In [ ]:
from IPython.display import Image
from IPython.core.display import HTML
Image(url= "https://i.postimg.cc/SQ1F9tPv/optimal-policy.png")

2b)

No matter what inital values are set, the optimal policy will still be the same. However, if the initial matrix contains big numbers, more iterations will be needed in order for the matrix to converge. This is due to the discount rate with after each iteration takes the historical rewards values less into account. The oldest historical rewards values, namely the initial values, is therefore taken into account the least. As one single algorithm is used for all iterations, the effect from the initial value will be negligible after a big number of iterations.

# Question 3

In this question, a Q-table for the 'NChain-v0' environment will be created based on the code given for the 'Frozen Lake' environment.


In [ ]:
pip install gym

In [ ]:
import gym
import numpy as np
import random
import math

In [ ]:
#Create the 'NChain-v0' environment
env = gym.make('NChain-v0')

In [ ]:
#Print the size of the action resp. state space

print("Action Space {}".format(env.action_space))
print("State Space {}".format(env.observation_space))

Action Space Discrete(2)
State Space Discrete(5)


In [ ]:
# Parameters for the Q-learning algorithm
num_episodes = 500 #20000 #60000
gamma = 0.95 #0.99
learning_rate = 0.1 #0.95 #0.85
epsilon = 0.5 #1 #0.15 #0.1

# initialize the Q table
Q = np.zeros([5, 2])
Q

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
#Q-learning model taken from the 'Frozen Lake' example
for _ in range(num_episodes):
	state = env.reset()
	done = False
	while done == False:
        # First we select an action:
		if random.uniform(0, 1) < epsilon: # Flip a skewed coin
			action = env.action_space.sample() # Explore action space
		else:
			action = np.argmax(Q[state,:]) # Exploit learned values
        # Then we perform the action and receive the feedback from the environment
		new_state, reward, done, info = env.step(action)
        # Finally we learn from the experience by updating the Q-value of the selected action
		update = reward + (gamma*np.max(Q[new_state,:])) - Q[state, action]
		Q[state,action] += learning_rate*update 
		state = new_state

In [ ]:
#Printing the Q table
Q

array([[61.17578161, 59.9919813 ],
       [64.53830675, 60.96944918],
       [69.13579502, 62.10568061],
       [72.38577523, 64.33071915],
       [81.97569491, 69.29297027]])

# Question 4

4a)

Below you will find an illustration for the Markov Decision Process for the 'NChain-v0' environment (copied from the assignment).

![alt text](https://i.postimg.cc/rwMKQdSk/chain-mdp.png)

Translating this illustration into code is based on the code for the value iteration in question 2. One major difference is that the rewards in this environment is much stronger connected to the transition between states compared to the environment in question 2. Therefore, we chose to not start with a reward matrix, but rather to give a reward of 2 if the backward action (b) is successful, 0 if the forward action (f) is successful in state 0, 1, 2 & 3, and 10 if the forward action (f) is successful in state 4. This is made in the method ```maxValue_new```. Small adaptations were also made as this observation space is best described by a 1x5 matrix.


In [ ]:
#Calculating the expected reward for each action in a certain state based on the given reward distribution and the historical rewards given (upd).
#The highest expected reward for any action is returned.
def maxValue_new(s, upd):
    if (s == 4):
        f = 0.8*(10+0.95*upd[s])+0.2*(2+0.95*upd[0])
        b = 0.8*(2+0.95*upd[0])+0.2*(10+0.95*upd[s])
    else:
        f = 0.8*(0.95*upd[s+1])+0.2*(2+0.95*upd[0])
        b = 0.8*(2+0.95*upd[0])+0.2*(0.95*upd[s+1])
    return max(f, b)

In [ ]:
def iterate(nr):
    temp = [0.0, 0.0, 0.0, 0.0, 0.0]
    
    #An inital value iteration is made
    for i in range(0,5):
        temp[i] = maxValue_new(i, [0.0, 0.0, 0.0, 0.0, 0.0]) #Highest expected reward for each state is calculated with no historical rewards given (upd is zero).

    #Additional value iterations are mode
    if (nr > 1):
        for i in range(nr-1):
            temp2 = [0.0, 0.0, 0.0, 0.0, 0.0]
            for i in range(0,5):
                temp2[i] = maxValue_new(i, temp) #Highest expected reward for each state is calculated based on historical rewards calculated in the last iteration
            temp = temp2
    return temp #Return the reward matrix calculated based on n iterations

print(iterate(500))

[61.37948159948314, 64.89128959948314, 69.51208959948313, 75.59208959948315, 83.59208959948315]


Comparing the Q-table at the end of question 3 with the table for the optimal value function just above, gives results that almost exactly follows the relationship between $Q^*(s,a)$ and $V^*(s)$ as stated in the assignment:

$$V^*(s) = \max_{a\in A} Q^*(s,a).$$


Below, the result of both the q-learning algoritm as well as value iteration algoritm is displayed. As expected the values are almost identicial. However, there is a slight difference between the values in each state. This could partly depend on the exploration rate that exist in the q-learning method (which is currently split evenly between exploration and exploatation). Moreover, the low learning rate requires a large amount of iterations for the values to converge. 

| | | |  
|----------|----------|---------|  
|61.2|60.0|
|64.5|61.0|  
|69.1|62.1|  
|72.4|64.3|
|82.0|69.3| 

| | | 
|----------|----------|
|61.4|
|64.9|
|69.5|
|75.6|
|83.6|



4b)

Running a Reinforcement Learning model without any exploration could be called a greedy policy, in which the agent always takes the action with the highest expected value. An everyday example could be when a person (Mr. Smith) decides what restaurant too choose. With a greedy policy, Mr. Smith would decide for the restaurant which has given Mr. Smith the highest satisfaction in the past.
However, with such a greedy policy Mr. Smith risks missing out of other restaurants which could bring him an even higher satisfaction than what he has experienced in the past. As Mr. Smith has not visited all restaurants, there are many restaurants with an unknown expected satisfaction value, which he is not able choose with a greedy policy.

Instead, Mr. Smith could do a so called epsilon-greedy policy, where he uses the greedy policy with a probability of 1-epsilon and takes a random choice with a probability of epsilon. With this epsilon-greedy policy, Mr. Smith will eventually visit all restaurants and thus find out about the satisfaction value for each restaurant. Mr. Smith of course risks choosing a restaurant with a low satisfaction value when doing a random choice. As he uses the greedy policy a certain share of the decision, he will be certain to get a high satisfaction these times.

Described more abstractly, with a greedy policy the RL model risks not exploring the whole action space as it is only making decisions based on previous action. The solution to this is to use a epsilon-greedy-policy, which some times makes decisions according to the greedy policy and some times make decisions on random with the aim to find even higher rewards.


#Question 5

5a)

**Decision trees**

A decision tree is a way of defining something based on a number of binary separations. A decision tree consist of the root, nodes, and leafs (see picture below). To build a tree, data from a dataset consisting of multiple features and one target is needed. The target is the question that is supposed to be answered by using a decision tree, e.g. does the patient from sample X has a heart disease? This is done be answering a few subquestion, called separations. To define what separation to put in the root, the gini impurity is calculated for all separations. Gini impurity can be described as the measure of how often an element in a set is wrongly labeled. Therefore, a low “gini-score” is preferable. The separation with the lowest gin-score is therefore set as the root of the tree.

Out of a decision tree, a random forest can be built. This is done since regular decision trees are easy to interpret, but not good when new samples are to be classified. 

First thing to do when creating a random forest is to create a bootstrap dataset, which basically consist of randomly selected samples from the original dataset. In the bootstrap dataset, samples could be used multiple times. To build the tree, two random variables from the bootstrap dataset are selected and the one with the lowest gini-score gets selected as the root. After that the same procedure goes for the following nodes, with the exception that the same column can’t be selected twice. When all variables are placed in the tree, a new random tree is created through the same procedure as described above. This is repeated as many times as possible.

When a new sample is to be classified, the sample is run through all trees and the classifications from the different trees are counted. The option with the most “votes” is defined the answer.

7.23


In [11]:
Image(url= "https://i.postimg.cc/3x8TzMM1/leafnode.jpg")

5b)

 **Supervised learning** is the process of learning a function that generates an output from a certain input based on multiple similar examples of inputs and outputs.

**Reinforcement learning** is another example of machine learning where the function learns to make a sequence of decisions. The optimal solutions is reached through assigning either rewards or penalties for certain actions. The goal of the function is to maximise the total reward. It is the programmer that sets the rewards and penalties. However, no hints are given regarding how to maximise the output. 

The biggest difference between the to learning algoritms is that supervised learning maps labeled input to known output and reinforcement learning follows a trail-and error method. The main tasks in the first-mentioned learning method is that the main task here is regression and classification. In reinforcement learning, there are multiple tasks that can be done, e.g. MDP and exploitation and exploration. Moreover, supervised learning aims to generate a formula given similar input-output-pairs, whereas reinforcement learning aims to make an algoritm that interacts with an environment by themselves. Another difference is that the data in supervised learning is labeled whereas the reinforcement learning has no predefined data. 